### PR TITLE
Add openmeeg math

### PR DESCRIPTION
**Pull request by massich**

### CODE REVIEW

**Comment by massich** [comment]
This is a good example of [CMake](https://github.com/preshing/CMakeDemo)

**Comment by agramfort** [comment]
could it be a pb where int are int32 by defualt on windows?

**Comment by agramfort** [comment]
all green? shall I merge?

**Comment by massich** [comment]
not yet I want to check the include_directories and remove 2 comments

**Comment by agramfort** [comment]
k

**Comment by agramfort** [comment]
🍺

**Pull request merged**
